server:
  port: 8081

spring:
  application:
    name: dubbo-example-consumer

dubbo:
  registry:
#    address: N/A
      address: zookeeper://127.0.0.1:2181
  #    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  protocol:
    name: dubbo
    port: 12345
