spring:
  application:
    name: dubbo-example-provider

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 12345
  scan:
    basePackages: shuaicj.example.dubbo.provider.service

helloService:
  version: 0.0.1